package cn.sdp.pkv.store.model;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SerialObj.proto

public final class SerialObj {
  private SerialObj() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SerialObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 cols = 1 [packed = true];
    /**
     * <code>repeated int32 cols = 1 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getColsList();
    /**
     * <code>repeated int32 cols = 1 [packed = true];</code>
     */
    int getColsCount();
    /**
     * <code>repeated int32 cols = 1 [packed = true];</code>
     */
    int getCols(int index);

    // repeated string contents = 2;
    /**
     * <code>repeated string contents = 2;</code>
     */
    java.util.List<java.lang.String>
    getContentsList();
    /**
     * <code>repeated string contents = 2;</code>
     */
    int getContentsCount();
    /**
     * <code>repeated string contents = 2;</code>
     */
    java.lang.String getContents(int index);
    /**
     * <code>repeated string contents = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentsBytes(int index);

    // optional int64 timestamp = 3;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code SerialObject}
   */
  public static final class SerialObject extends
      com.google.protobuf.GeneratedMessage
      implements SerialObjectOrBuilder {
    // Use SerialObject.newBuilder() to construct.
    private SerialObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SerialObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SerialObject defaultInstance;
    public static SerialObject getDefaultInstance() {
      return defaultInstance;
    }

    public SerialObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SerialObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cols_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              cols_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                cols_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                cols_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                contents_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              contents_.add(input.readBytes());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cols_ = java.util.Collections.unmodifiableList(cols_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          contents_ = new com.google.protobuf.UnmodifiableLazyStringList(contents_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SerialObj.internal_static_SerialObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SerialObj.internal_static_SerialObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SerialObj.SerialObject.class, SerialObj.SerialObject.Builder.class);
    }

    public static com.google.protobuf.Parser<SerialObject> PARSER =
        new com.google.protobuf.AbstractParser<SerialObject>() {
      public SerialObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SerialObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SerialObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int32 cols = 1 [packed = true];
    public static final int COLS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> cols_;
    /**
     * <code>repeated int32 cols = 1 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getColsList() {
      return cols_;
    }
    /**
     * <code>repeated int32 cols = 1 [packed = true];</code>
     */
    public int getColsCount() {
      return cols_.size();
    }
    /**
     * <code>repeated int32 cols = 1 [packed = true];</code>
     */
    public int getCols(int index) {
      return cols_.get(index);
    }
    private int colsMemoizedSerializedSize = -1;

    // repeated string contents = 2;
    public static final int CONTENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList contents_;
    /**
     * <code>repeated string contents = 2;</code>
     */
    public java.util.List<java.lang.String>
        getContentsList() {
      return contents_;
    }
    /**
     * <code>repeated string contents = 2;</code>
     */
    public int getContentsCount() {
      return contents_.size();
    }
    /**
     * <code>repeated string contents = 2;</code>
     */
    public java.lang.String getContents(int index) {
      return contents_.get(index);
    }
    /**
     * <code>repeated string contents = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentsBytes(int index) {
      return contents_.getByteString(index);
    }

    // optional int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      cols_ = java.util.Collections.emptyList();
      contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getColsList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(colsMemoizedSerializedSize);
      }
      for (int i = 0; i < cols_.size(); i++) {
        output.writeInt32NoTag(cols_.get(i));
      }
      for (int i = 0; i < contents_.size(); i++) {
        output.writeBytes(2, contents_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < cols_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(cols_.get(i));
        }
        size += dataSize;
        if (!getColsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        colsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < contents_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(contents_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getContentsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SerialObj.SerialObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SerialObj.SerialObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SerialObj.SerialObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SerialObj.SerialObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SerialObj.SerialObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SerialObj.SerialObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SerialObj.SerialObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SerialObj.SerialObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SerialObj.SerialObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SerialObj.SerialObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SerialObj.SerialObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SerialObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SerialObj.SerialObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SerialObj.internal_static_SerialObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SerialObj.internal_static_SerialObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SerialObj.SerialObject.class, SerialObj.SerialObject.Builder.class);
      }

      // Construct using SerialObj.SerialObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cols_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SerialObj.internal_static_SerialObject_descriptor;
      }

      public SerialObj.SerialObject getDefaultInstanceForType() {
        return SerialObj.SerialObject.getDefaultInstance();
      }

      public SerialObj.SerialObject build() {
        SerialObj.SerialObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SerialObj.SerialObject buildPartial() {
        SerialObj.SerialObject result = new SerialObj.SerialObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          cols_ = java.util.Collections.unmodifiableList(cols_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cols_ = cols_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          contents_ = new com.google.protobuf.UnmodifiableLazyStringList(
              contents_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.contents_ = contents_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SerialObj.SerialObject) {
          return mergeFrom((SerialObj.SerialObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SerialObj.SerialObject other) {
        if (other == SerialObj.SerialObject.getDefaultInstance()) return this;
        if (!other.cols_.isEmpty()) {
          if (cols_.isEmpty()) {
            cols_ = other.cols_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColsIsMutable();
            cols_.addAll(other.cols_);
          }
          onChanged();
        }
        if (!other.contents_.isEmpty()) {
          if (contents_.isEmpty()) {
            contents_ = other.contents_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureContentsIsMutable();
            contents_.addAll(other.contents_);
          }
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SerialObj.SerialObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SerialObj.SerialObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 cols = 1 [packed = true];
      private java.util.List<java.lang.Integer> cols_ = java.util.Collections.emptyList();
      private void ensureColsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cols_ = new java.util.ArrayList<java.lang.Integer>(cols_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 cols = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getColsList() {
        return java.util.Collections.unmodifiableList(cols_);
      }
      /**
       * <code>repeated int32 cols = 1 [packed = true];</code>
       */
      public int getColsCount() {
        return cols_.size();
      }
      /**
       * <code>repeated int32 cols = 1 [packed = true];</code>
       */
      public int getCols(int index) {
        return cols_.get(index);
      }
      /**
       * <code>repeated int32 cols = 1 [packed = true];</code>
       */
      public Builder setCols(
          int index, int value) {
        ensureColsIsMutable();
        cols_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cols = 1 [packed = true];</code>
       */
      public Builder addCols(int value) {
        ensureColsIsMutable();
        cols_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cols = 1 [packed = true];</code>
       */
      public Builder addAllCols(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureColsIsMutable();
        super.addAll(values, cols_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cols = 1 [packed = true];</code>
       */
      public Builder clearCols() {
        cols_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated string contents = 2;
      private com.google.protobuf.LazyStringList contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureContentsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          contents_ = new com.google.protobuf.LazyStringArrayList(contents_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public java.util.List<java.lang.String>
          getContentsList() {
        return java.util.Collections.unmodifiableList(contents_);
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public int getContentsCount() {
        return contents_.size();
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public java.lang.String getContents(int index) {
        return contents_.get(index);
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentsBytes(int index) {
        return contents_.getByteString(index);
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public Builder setContents(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentsIsMutable();
        contents_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public Builder addContents(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentsIsMutable();
        contents_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public Builder addAllContents(
          java.lang.Iterable<java.lang.String> values) {
        ensureContentsIsMutable();
        super.addAll(values, contents_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public Builder clearContents() {
        contents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contents = 2;</code>
       */
      public Builder addContentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentsIsMutable();
        contents_.add(value);
        onChanged();
        return this;
      }

      // optional int64 timestamp = 3;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SerialObject)
    }

    static {
      defaultInstance = new SerialObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SerialObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SerialObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SerialObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SerialObj.proto\"E\n\014SerialObject\022\020\n\004col" +
      "s\030\001 \003(\005B\002\020\001\022\020\n\010contents\030\002 \003(\t\022\021\n\ttimesta" +
      "mp\030\003 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SerialObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SerialObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SerialObject_descriptor,
              new java.lang.String[] { "Cols", "Contents", "Timestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
